In [1]:
import pandas as pd 
import numpy as np 
import re 
import os
import sys
import urllib.request
import json
from tabulate import tabulate

In [2]:
tmp = pd.read_csv('categorized_performance.csv')
tmp[tmp['상품명'].str.contains('이봉원')]

,Unnamed: 0,방송일시,노출(분),상품명,상품군,판매단가,취급액,방송일시_yymmdd,방송일시_hhmmss,seconds,방송일시_hhmm,ratings_mean,cat1,cat2,cat3,cat4
328,328,2019-01-01 15:00:00,20.0,뽕셰프 이봉원 특갈비탕 12팩,농수축,60900,14113000.0,2019-01-01,15:00:00,900,15:00,0.006249,식품,냉동/간편조리식품,즉석국/즉석탕,NaN
329,329,2019-01-01 15:20:00,20.0,뽕셰프 이봉원 특갈비탕 12팩,농수축,60900,32395000.0,2019-01-01,15:20:00,920,15:20,0.005833,식품,냉동/간편조리식품,즉석국/즉석탕,NaN
330,330,2019-01-01 15:40:00,20.0,뽕셰프 이봉원 특갈비탕 12팩,농수축,60900,39669000.0,2019-01-01,15:40:00,940,15:40,0.006284,식품,냉동/간편조리식품,즉석국/즉석탕,NaN
331,331,2019-01-03 17:00:00,20.0,뽕셰프 이봉원 특갈비탕 12팩,농수축,60900,16350000.0,2019-01-03,17:00:00,1020,17:00,0.005029,식품,냉동/간편조리식품,즉석국/즉석탕,NaN
332,332,2019-01-03 17:20:00,20.0,뽕셰프 이봉원 특갈비탕 12팩,농수축,60900,33015000.0,2019-01-03,17:20:00,1040,17:20,0.005519,식품,냉동/간편조리식품,즉석국/즉석탕,NaN
333,333,2019-01-03 17:40:00,20.0,뽕셰프 이봉원 특갈비탕 12팩,농수축,60900,27284000.0,2019-01-03,17:40:00,1060,17:40,0.005459,식품,냉동/간편조리식품,즉석국/즉석탕,NaN
7273,7273,2019-01-16 17:00:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,28939000.0,2019-01-16,17:00:00,1020,17:00,0.005029,식품,축산,쇠고기,수입산쇠고기
7274,7274,2019-01-16 17:20:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,38626000.0,2019-01-16,17:20:00,1040,17:20,0.005519,식품,축산,쇠고기,수입산쇠고기
7275,7275,2019-01-16 17:40:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,40823000.0,2019-01-16,17:40:00,1060,17:40,0.005459,식품,축산,쇠고기,수입산쇠고기
7276,7276,2019-01-19 18:20:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,25532000.0,2019-01-19,18:20:00,1100,18:20,0.004915,식품,축산,쇠고기,수입산쇠고기
7277,7277,2019-01-19 18:40:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,53751000.0,2019-01-19,18:40:00,1120,18:40,0.005017,식품,축산,쇠고기,수입산쇠고기
7278,7278,2019-01-25 18:00:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,26390000.0,2019-01-25,18:00:00,1080,18:00,0.006072,식품,축산,쇠고기,수입산쇠고기
7279,7279,2019-01-25 18:20:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,33516000.0,2019-01-25,18:20:00,1100,18:20,0.004915,식품,축산,쇠고기,수입산쇠고기
7280,7280,2019-01-25 18:40:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,44255000.0,2019-01-25,18:40:00,1120,18:40,0.005017,식품,축산,쇠고기,수입산쇠고기
7281,7281,2019-01-28 18:00:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,18166000.0,2019-01-28,18:00:00,1080,18:00,0.006072,식품,축산,쇠고기,수입산쇠고기
7282,7282,2019-01-28 18:20:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,24841000.0,2019-01-28,18:20:00,1100,18:20,0.004915,식품,축산,쇠고기,수입산쇠고기
7283,7283,2019-01-28 18:40:00,20.0,이봉원 정직한 안창살 + 갈비살구이,농수축,59900,43805000.0,2019-01-28,18:40:00,1120,18:40,0.005017,식품,축산,쇠고기,수입산쇠고기

**<제품명에서 제거된 것 + 이에 사용한 정규표현식 ('|'로 구분)>**

**1. 괄호를 포함 혹은 포함하지 않은 결제관련 정보(무이자, 일시불, 이자 등)**

    \(?무이자\)?\s?|\(?일시불\)?\s?|\(?초특가\)?\s?|\(?무\)\s?|\(?유\)\s?|\(?일\)\s?

**2. 제품명 맨 앞, 맨 끝에 붙어있는 괄호들 (40인치) (특상품) (초특가) 등은 제품 카테고리와 무방하다 생각하여 삭제**

    \(.{1,10}\)$|^\(.?\)

**3. ~패키지, ~종, 세트, n+n, 더블팩, 싱글팩 등 제품 수량단위와 관련한 것**

    \s?패키지\s?|[0-9]+종.*|세트|더블팩|싱글팩|[0-9]{1,2}\+[0-9]{1,2}

# Preprocess (민수 ipynb 참고)

In [4]:
t = pd.read_excel('2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터_v1_200818.xlsx', skiprows=1)
print(t.isnull().sum(),'\n')
t=t[t['상품군']!='무형']
print(t.isnull().sum(),'\n')
t[t['취급액'].isnull()]
t.취급액 = t.취급액.fillna(0)
print(t.isnull().sum())
t

방송일시         0
노출(분)    16784
마더코드         0
상품코드         0
상품명          0
상품군          0
판매단가         0
취급액       2930
dtype: int64

방송일시         0
노출(분)    16784
마더코드         0
상품코드         0
상품명          0
상품군          0
판매단가         0
취급액       1993
dtype: int64

방송일시         0
노출(분)    16784
마더코드         0
상품코드         0
상품명          0
상품군          0
판매단가         0
취급액          0
dtype: int64

,방송일시,노출(분),마더코드,상품코드,상품명,상품군,판매단가,취급액
0,2019-01-01 06:00:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,2099000.0
1,2019-01-01 06:00:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,4371000.0
2,2019-01-01 06:20:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,3262000.0
3,2019-01-01 06:20:00,NaN,100346,201079,테이트 여성 셀린니트3종,의류,39900,6955000.0
4,2019-01-01 06:40:00,20.0,100346,201072,테이트 남성 셀린니트3종,의류,39900,6672000.0
...,...,...,...,...,...,...,...,...
38299,2019-12-31 23:40:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,10157000.0
38300,2020-01-01 00:00:00,20.0,100448,201383,무이자쿠첸압력밥솥 10인용,주방,178000,50929000.0
38301,2020-01-01 00:00:00,NaN,100448,201390,일시불쿠첸압력밥솥 10인용,주방,168000,104392000.0
38302,2020-01-01 00:00:00,NaN,100448,201384,무이자쿠첸압력밥솥 6인용,주방,158000,13765000.0
38303,2020-01-01 00:00:00,NaN,100448,201391,일시불쿠첸압력밥솥 6인용,주방,148000,46608000.0

In [5]:
performance = pd.read_excel('2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터_v1_200818.xlsx', skiprows=1)
ratings = pd.read_excel('2020 빅콘테스트 데이터분석분야-챔피언리그_시청률 데이터.xlsx', skiprows=1)
performance = performance[performance['상품군']!='무형']
performance['취급액'] = performance['취급액'].fillna(0)
performance = performance.fillna(method='pad')
performance.drop(['마더코드','상품코드'], axis=1, inplace=True)
performance['방송일시_yymmdd'] = performance['방송일시'].apply(lambda x: str(x)[:10])
performance['방송일시_hhmmss'] = performance['방송일시'].apply(lambda x: str(x)[11:])

performance['seconds'] = performance['방송일시_hhmmss'].apply(lambda x: int(x[:2])*60 + int(x[3:5]))


performance.head()

,방송일시,노출(분),상품명,상품군,판매단가,취급액,방송일시_yymmdd,방송일시_hhmmss,seconds
0,2019-01-01 06:00:00,20.0,테이트 남성 셀린니트3종,의류,39900,2099000.0,2019-01-01,06:00:00,360
1,2019-01-01 06:00:00,20.0,테이트 여성 셀린니트3종,의류,39900,4371000.0,2019-01-01,06:00:00,360
2,2019-01-01 06:20:00,20.0,테이트 남성 셀린니트3종,의류,39900,3262000.0,2019-01-01,06:20:00,380
3,2019-01-01 06:20:00,20.0,테이트 여성 셀린니트3종,의류,39900,6955000.0,2019-01-01,06:20:00,380
4,2019-01-01 06:40:00,20.0,테이트 남성 셀린니트3종,의류,39900,6672000.0,2019-01-01,06:40:00,400

In [6]:
ratings = ratings.set_index('시간대')
ratings.mean(axis=1)
ratings.drop('월화수목금토일02:00-01:59', axis=0, inplace=True)

mean = ratings.mean(axis=1).values
ratings['mean'] = mean
ratings = ratings.reset_index()
ratings = ratings[['시간대','mean']]
ratings['시간대'] = ratings['시간대'].astype('datetime64[ns]')
ratings.set_index('시간대', inplace=True)

# 5단위로 시간대별 평균 집계
tmp = ratings[['mean']].resample('5T').mean().reset_index()
ratings = ratings.reset_index()
ratings = pd.merge(ratings, tmp, on='시간대', how='left')
ratings.head()

ratings.drop('mean_x', axis = 1, inplace= True)
ratings.rename({'mean_y':'ratings_mean'}, axis=1, inplace=True)
ratings['시간대'] = ratings['시간대'].astype(str)
ratings.head()

# 시간대에서 초단위 삭제
ratings['시간대'] = ratings['시간대'].apply(lambda x: x[-8:-3])
# 시분만 사용한 컬럼 생성
performance['방송일시_hhmm'] = performance['방송일시_hhmmss'].apply(lambda x: x[:-3])

performance = pd.merge(performance, ratings, left_on = '방송일시_hhmm', right_on = '시간대', how='left')
del performance['시간대']

performance.head()

,방송일시,노출(분),상품명,상품군,판매단가,취급액,방송일시_yymmdd,방송일시_hhmmss,seconds,방송일시_hhmm,ratings_mean
0,2019-01-01 06:00:00,20.0,테이트 남성 셀린니트3종,의류,39900,2099000.0,2019-01-01,06:00:00,360,06:00,0.002255
1,2019-01-01 06:00:00,20.0,테이트 여성 셀린니트3종,의류,39900,4371000.0,2019-01-01,06:00:00,360,06:00,0.002255
2,2019-01-01 06:20:00,20.0,테이트 남성 셀린니트3종,의류,39900,3262000.0,2019-01-01,06:20:00,380,06:20,0.002210
3,2019-01-01 06:20:00,20.0,테이트 여성 셀린니트3종,의류,39900,6955000.0,2019-01-01,06:20:00,380,06:20,0.002210
4,2019-01-01 06:40:00,20.0,테이트 남성 셀린니트3종,의류,39900,6672000.0,2019-01-01,06:40:00,400,06:40,0.001997

# 제품명 전처리

In [7]:
# 상품명 중복 제거
uniq_pname=performance['상품명'].unique()
print('\n<# of Unique pnameuct Name> : \n\t{}'.format(len(uniq_pname)))
np.set_printoptions(threshold=sys.maxsize)

# 추후 조합을 위해 전처리 이전 제품명과 이후 제품명을 저장합니다.
p_name = pd.DataFrame(data=uniq_pname, columns=['Before Process'])

# 제품명에서 불필요한 요소 전처리
ap=[]
re_stop = re.compile("""\([가-힣]{1,5}\+[가-힣]{1,5}\)|\(?무이자\)?\s?|\(?일시불\)?\s?|\(?초특가\)?\s?|\(?무\)\s?|\(?유\)\s?|\(?일\)\s?|무료체험|
|포함|국내[가-힣]+\s|무료설치|\s?신제품\s?|\s?패키지\s?|[0-9]+종|풀코디|set|SET|풀세트|[0-9]+세트|더블팩|싱글팩|[0-9]{1,2}\+[0-9]{1,2}|[0-9]{1,2}인용|[0-9]{1,2}박스|[0-9\.]{1,4}미터|[0-9\.]{1,4}kg|[0-9\.]{1,4}[kKgG]|[0-9]{1,3}[벌롤종단구대P개통병포미봉팩장gL매]|
|\s[0-9\.]{1,4}[Mm]|\(.{1,10}\)$|^\(.?\)|^[0-9]{2,4}\s|\s+[0-9]{2,4}\s|[0-9]{2,4}년\s|[0-9]{2,4}년형\s|시즌[0-9]|[0-9]{1,3}\%|\(.{1,20}\)$|기본형|고급형|오리지널|[대중소大中小]형|.{1,10}by|,|\s?총[0-9\s]|^[가-힣a-zA-Z]{3,3}의|
|S\/S|F\/W|f\/w|s\/s|[가-힣]+형\s|[슈퍼]{0,2}싱글|\s[SQK퀸킹]{1,2}\s|[SQK퀸킹]{1,2}$|[가-힣]{0,2}사이즈""")

remnants = re.compile('[",g\+lL-]\s|ml|_|\sx|[\[\]\］!"#$%&\'()*+,./:;<=>?@\^_`{|}~-]|\s종$|\s[0-9]+\s|\s{2,}')

for i in p_name['Before Process']:
    tmp = re_stop.sub(' ',i)
    tmp = tmp.strip()
    tmp = remnants.sub(' ',tmp)
    ap.append(tmp.strip())

# 전처리된 제품명 중복제거
p_name['After Process'] = ap
p_name.to_html('tmp.html')

ap = list(set(ap))

p_name

<# of Unique pnameuct Name> :
	1692

                        Before Process                     After Process
0                        테이트 남성 셀린니트3종                       테이트 남성 셀린니트
1                        테이트 여성 셀린니트3종                       테이트 여성 셀린니트
2                     오모떼 레이스 파운데이션 브라                  오모떼 레이스 파운데이션 브라
3        CERINI by PAT 남성 소프트 기모 릴렉스팬츠               PAT 남성 소프트 기모 릴렉스팬츠
4                          보코 리버시블 무스탕                       보코 리버시블 무스탕
...                                ...                               ...
1687                     조방할매 낙곱새 6팩세트                       조방할매 낙곱새 세트
1688  파격가 니봇 무선 진공 물걸레 로봇청소기 +뉴헤어드라이어기  파격가 니봇 무선 진공 물걸레 로봇청소기  뉴헤어드라이어기
1689                        램프쿡 자동회전냄비                        램프쿡 자동회전냄비
1690               벨라홈 스마트 멀티포트 1+1 세트                   벨라홈 스마트 멀티포트 세트
1691                     코몽트 기모 터틀넥 5종                        코몽트 기모 터틀넥

[1692 rows x 2 columns]

In [ ]:
print(ap)

In [ ]:
p_name

# 네이버 카테고리 검색기

**혜인**

ID: OpYVfNnlgdKhnWHmxlxa

PW: acYb7du6_E


**왕수**

ID: tdrEWZrN1ZQp9u0yqy3e

PW: 59Bl3ltKdX

In [8]:
# 네이버 검색 API를 이용하여 세부 카테고리를 검색합니다.
def naver_shop(keyword):
    client_id = "DWNxDn7nWmw_X5LC74yj"
    client_secret = "MFrEW9wCWI"
    keyword = keyword.strip()
    encText = urllib.parse.quote(keyword)
    url = "https://openapi.naver.com/v1/search/shop.json?query=" + encText + "&display=1" # json 결과
    # url = "https://openapi.naver.com/v1/search/shop.xml?query=" + encText # xml 결과
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        jsonString = response_body.decode('utf-8')
        j = json.loads(jsonString)
        if int(j['total']):
            c1 = j["items"][0]['category1']
            c2 = j["items"][0]["category2"]
            c3 = j["items"][0]["category3"]
            c4 = j["items"][0]["category4"]
            keyword2=''
        else : # 검색결과가 없을경우 모델명(숫자+알파벳 구성)과 사이즈(주로 한자어)를 제거하고 뒤에서부터 2개의 어절만으로 검색 재시도
            p_code = re.compile('[0-9a-zA-Z]+$|[一-龥]+$')
            keyword2 = p_code.sub(' ',keyword)
            keyword2 = keyword2.strip()
            keyword2 = p_code.sub(' ',keyword2)
            keyword2 = ' '.join(keyword2.split()[-2:])
            
            encText = urllib.parse.quote(keyword2)
            url = "https://openapi.naver.com/v1/search/shop.json?query=" + encText + "&display=1"
            request = urllib.request.Request(url)
            request.add_header("X-Naver-Client-Id",client_id)
            request.add_header("X-Naver-Client-Secret",client_secret)
            response = urllib.request.urlopen(request)
            rescode = response.getcode()
            
            if(rescode==200):
                response_body = response.read()
                jsonString = response_body.decode('utf-8')
                j = json.loads(jsonString)
                if int(j['total']):
                    c1 = j["items"][0]['category1']
                    c2 = j["items"][0]["category2"]
                    c3 = j["items"][0]["category3"]
                    c4 = j["items"][0]["category4"]
                else :
                    print(keyword,'->',keyword2)
                    print('>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<')
                    c1, c2, c3, c4 = '', '', '', ''
            else :
                print("Error Code:" + rescode)
    else:
        print("Error Code:" + rescode)
    return [keyword,c1,c2,c3,c4,keyword2]

In [9]:
from tqdm import tqdm_notebook

cat_df = pd.DataFrame(columns = ['pname','cat1','cat2','cat3','cat4','pname2'])

for item in tqdm_notebook(ap):
#     print(item)
    ns = naver_shop(item)
    cat_df=cat_df.append(pd.DataFrame([ns],columns=['pname','cat1','cat2','cat3','cat4','pname2']), ignore_index=True)

cat_df

HBox(children=(IntProgress(value=0, max=1266), HTML(value='')))

탕요일 -> 탕요일
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
메이듀 남성 린넨 블렌디드 슬립온 -> 블렌디드 슬립온
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
크로커다일 에어스킨 감탄브라 -> 에어스킨 감탄브라
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
아리스토우 남성기모티셔츠 -> 아리스토우 남성기모티셔츠
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
바다원  더 그릴 아구채  양태채  쥐포채  소스 -> 쥐포채 소스
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
비가린 배추김치 -> 비가린 배추김치
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
특大손질갑오징어 -> 특大손질갑오징어
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
AAE LA갈비 -> AAE LA갈비
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
에트로 프로푸미 웨이스트백 -> 프로푸미 웨이스트백
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
PAT 남성 에어 카타티셔츠 -> 에어 카타티셔츠
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
코펜하겐럭스 세미와이드팬츠 -> 코펜하겐럭스 세미와이드팬츠
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
삼성5도어냉장고 T9000 RF84R9203S8   시카고커트러리5p세트 -> RF84R9203S8 시카고커트러리5p세트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
한샘 뉴퍼스티지R 리클라이너 -> 뉴퍼스티지R 리클라이너
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
뽕셰프 이봉원 특갈비탕 -> 이봉원 특갈비탕
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
레이프릴 더블엑스 매직니퍼팬티 -> 더블엑스 매직니퍼팬티
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
남해바다 손질왕꼬막살세트 -> 남해바다 손질왕꼬막살세트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
USPA화이트라벨 여성트랙수트 -> USPA화이트라벨 여성트랙수트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
한삼인순홍삼진 -> 한삼인순홍삼진
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
페르소나 고기능 안전스틱 -> 고기능 안전스틱
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
삼익가구 LED 제니비 침대 -> 제니비 침대
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
마르엘라로사티 에코무스탕 -> 마르엘라로사티 에코무스탕
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
메이듀 여성 린넨 블렌디드 슬립온 -> 블렌디드 슬립온
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
우리바다 손질왕꼬막 -> 우리바다 손질왕꼬막
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
리복 남성 스피드윅 웜웨어 -> 스피드윅 웜웨어
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
황제진액 철갑상어 -> 황제진액 철갑상어
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
크리스티나앤코 이지웨어세트 -> 크리스티나앤코 이지웨어세트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
리복 여성 스피드윅 웜웨어 -> 스피드윅 웜웨어
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
몬테밀라노 크루즈 이지웨어 -> 크루즈 이지웨어
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
루시헨느 레이스 홀리데이 란쥬 -> 홀리데이 란쥬
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
더커진거창특등급사과 -> 더커진거창특등급사과
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
창녕 마늘양파듬뿍삼계탕 -> 창녕 마늘양파듬뿍삼계탕
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
뱅뱅 여성 간절기 데님팬츠  KQE251 KQE253 KQE255 -> 데님팬츠 KQE251
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
거창특등급사과 -> 거창특등급사과
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
아가타 컬러풀에디션 -> 아가타 컬러풀에디션
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
코펜하겐럭스 판초니트 -> 코펜하겐럭스 판초니트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
USPA화이트라벨 남성트랙수트 -> USPA화이트라벨 남성트랙수트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
가이거  제니스시계 주얼리세트 -> 제니스시계 주얼리세트
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
뱅뱅 남성 간절기 데님팬츠  GQE772 GQE774 GQE776 -> 데님팬츠 GQE772
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<
크리스티나앤코 기모밴딩팬츠 -> 크리스티나앤코 기모밴딩팬츠
>>>>>>>>>>>>>>>>>>>>Search Failed!<<<<<<<<<<<<<<<<<<<<

                           pname    cat1       cat2     cat3     cat4 pname2
0     LG 코드제로 무선청소기 A940  A948SA  디지털/가전       생활가전      청소기    무선청소기
1                    경남제약 레모나 S산      식품       건강식품     비타민제     비타민C
2                     리복 델타 언더셔츠    패션의류  남성언더웨어/잠옷       러닝
3                뉴욕맘 목화솜행주 항균수세미   생활/건강       주방용품     주방잡화       행주
4                    브람스안마의자 럭셔리   생활/건강       안마용품     안마의자
...                          ...     ...        ...      ...      ...    ...
1261               푸마 프레쉬 미들 드로즈    패션의류  남성언더웨어/잠옷       팬티
1262      캐리어 벽걸이에어컨 6형 ARC06NQT  디지털/가전       계절가전      에어컨  벽걸이형에어컨
1263                  삭루츠 투웨이 백팩    패션잡화       여성가방       백팩
1264                     삭루츠 토트백    패션잡화       여성가방      토트백
1265             골드파일 카로 여행가방 세트    패션잡화   여행용가방/소품  중대형 캐리어

[1266 rows x 6 columns]

In [10]:
len(cat_df)
unknown_ratio = len(cat_df[cat_df['cat1']==''])/len(cat_df)*100
print("알아내지 못한 카테고리 비율 : ", round(unknown_ratio,3),"%")

알아내지 못한 카테고리 비율 :  3.081 %

### 찾지 못한 키워드는


1) 제품코드일 가능성이 높은 알파벳+숫자만으로 이루어진 덩어리 제거

2) 제품 명사일 가능성이 높은 맨 뒷 2어절 탐색 >>>>>>>>>>>>>>>>>>>>> 검색기 내부에서 작동




**그래도 못찾으면?**


1) 유사도 기준 참조

# 유사도 탐색기

## HOW? : Jaccard_Similarity

> 문장을 명사단위로 쪼갠 뒤 두 문장간 (겹치는 명사의 개수) / (총 명사의 수) 로 구하는 유사도

>> 예시) Jaccard('특대형 한방닭백숙', '김개똥의 닭백숙 세트') --> ('특','특대형','한방','닭','닭백숙','백숙'), ('김개똥','닭','닭백숙','백숙','세트)

>> A&B = 6개(3쌍) ('닭','백숙','닭백숙')

>> A|B = 11개

>> Jaccard_sim = 6/11 = 54.5%

In [11]:
from tqdm import tqdm_notebook
from konlpy.tag import Kkma
kkma=Kkma()
def jaccard_sim(doc1, doc2):
    doc1 = kkma.nouns(doc1)
    doc2 = kkma.nouns(doc2)
    u_doc1 = set(doc1)
    u_doc2 = set(doc2)
    return len(u_doc1 & u_doc2) / len(u_doc1 | u_doc2)

In [12]:
cat_df.to_csv('fisrt_search_cat.csv')

In [13]:
# cat_df = pd.read_csv('좀더_전처리_카테고리결과.csv',index_col=0)
unknown = cat_df[cat_df['cat1']=='']
known = cat_df[cat_df['cat1']!='']
for i in tqdm_notebook(range(len(unknown))):
    best_sim = 0
    print(unknown.iloc[i].pname)
    for j in tqdm_notebook(range(len(known))):
        sim = jaccard_sim(unknown.iloc[i].pname,known.iloc[j].pname)
        if sim > best_sim :
            best_sim = sim
            best_ind = j
            print(best_sim)
    unknown.iloc[i].cat1 = known.iloc[best_ind].cat1
    unknown.iloc[i].cat2 = known.iloc[best_ind].cat2
    unknown.iloc[i].cat3 = known.iloc[best_ind].cat3
    unknown.iloc[i].cat4 = known.iloc[best_ind].cat4
    print(known.iloc[best_ind].cat1, known.iloc[best_ind].cat2,known.iloc[best_ind].cat3,known.iloc[best_ind].cat4)

HBox(children=(IntProgress(value=0, max=39), HTML(value='')))

탕요일

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.14285714285714285

식품 냉동/간편조리식품 즉석국/즉석탕
메이듀 남성 린넨 블렌디드 슬립온

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.08333333333333333
0.1
0.2727272727272727

패션의류 여성의류 블라우스/셔츠
크로커다일 에어스킨 감탄브라

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.07142857142857142
0.25
0.3

패션의류 여성언더웨어/잠옷 브라팬티세트
아리스토우 남성기모티셔츠

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.08333333333333333
0.16666666666666666
0.18181818181818182
0.36363636363636365
0.5714285714285714

패션의류 남성의류 티셔츠
바다원  더 그릴 아구채  양태채  쥐포채  소스

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.05263157894736842
0.058823529411764705

식품 수산 생선 장어
비가린 배추김치

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.08333333333333333
0.14285714285714285

식품 김치 포기김치
특大손질갑오징어

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.08333333333333333
0.5
0.8

식품 수산 해산물/어패류 오징어
AAE LA갈비

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.125
0.16666666666666666

식품 축산 축산가공식품 쇠고기양념육
에트로 프로푸미 웨이스트백

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.07142857142857142
0.1
0.18181818181818182
0.2
0.5555555555555556

패션잡화 여성가방 크로스백
PAT 남성 에어 카타티셔츠

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.08333333333333333
0.1111111111111111
0.2222222222222222
0.3333333333333333
0.5
0.75

스포츠/레저 골프 골프의류 티셔츠
코펜하겐럭스 세미와이드팬츠

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.05555555555555555
0.06666666666666667
0.08333333333333333
0.09090909090909091
0.125
0.14285714285714285
0.5

패션의류 여성의류 바지
삼성5도어냉장고 T9000 RF84R9203S8   시카고커트러리5p세트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.05
0.17647058823529413
0.5

디지털/가전 주방가전 냉장고 양문형냉장고
한샘 뉴퍼스티지R 리클라이너

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.07142857142857142
0.08333333333333333
0.5

가구/인테리어 거실가구 소파 리클라이너소파
뽕셰프 이봉원 특갈비탕

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.07142857142857142
0.07692307692307693
0.1

식품 냉동/간편조리식품 즉석국/즉석탕
레이프릴 더블엑스 매직니퍼팬티

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.0625
0.11764705882352941
0.25
0.26666666666666666

패션의류 여성언더웨어/잠옷 보정속옷 거들
남해바다 손질왕꼬막살세트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.07692307692307693
0.1
0.14285714285714285
0.16666666666666666
0.2

식품 수산 해산물/어패류 꼬막
USPA화이트라벨 여성트랙수트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.08333333333333333
0.1111111111111111
0.36363636363636365
0.4
0.4444444444444444

패션의류 여성의류 티셔츠
한삼인순홍삼진

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

패션의류 여성의류 티셔츠
페르소나 고기능 안전스틱

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.05
0.08333333333333333

가구/인테리어 카페트/러그 러그
삼익가구 LED 제니비 침대

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.07692307692307693
0.09090909090909091
0.1
0.125
0.6666666666666666

가구/인테리어 침실가구 침대 침대프레임
마르엘라로사티 에코무스탕

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.07142857142857142
0.13333333333333333
0.5
0.5555555555555556

패션의류 여성의류 청바지
메이듀 여성 린넨 블렌디드 슬립온

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.08333333333333333
0.1111111111111111
0.2727272727272727

패션의류 여성의류 블라우스/셔츠
우리바다 손질왕꼬막

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.16666666666666666
0.2
0.25

식품 수산 해산물/어패류 꼬막
리복 남성 스피드윅 웜웨어

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.21428571428571427
0.5454545454545454

패션의류 남성의류 트레이닝복
황제진액 철갑상어

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

패션의류 남성의류 트레이닝복
크리스티나앤코 이지웨어세트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.0625
0.06666666666666667
0.07142857142857142
0.11764705882352941
0.38461538461538464
0.5
0.5454545454545454

패션의류 여성의류 코디세트
리복 여성 스피드윅 웜웨어

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.21428571428571427
0.5454545454545454

패션의류 남성의류 트레이닝복
몬테밀라노 크루즈 이지웨어

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.23076923076923078

패션의류 여성의류 레깅스
루시헨느 레이스 홀리데이 란쥬

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.1111111111111111
0.11764705882352941

패션의류 여성언더웨어/잠옷 브라팬티세트
더커진거창특등급사과

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.18181818181818182

식품 농산물 과일 포도
창녕 마늘양파듬뿍삼계탕

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.1

식품 축산 축산가공식품 삼계탕
뱅뱅 여성 간절기 데님팬츠  KQE251 KQE253 KQE255

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.2727272727272727
0.4

패션의류 여성의류 청바지
거창특등급사과

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.2

식품 농산물 과일 포도
아가타 컬러풀에디션

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.07142857142857142
0.1875
0.3333333333333333
0.5

화장품/미용 베이스메이크업 파운데이션 쿠션형
코펜하겐럭스 판초니트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.058823529411764705
0.07142857142857142
0.07692307692307693
0.1
0.16666666666666666
0.4166666666666667

패션의류 여성의류 바지
USPA화이트라벨 남성트랙수트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.08333333333333333
0.1
0.1111111111111111
0.25
0.4444444444444444

패션의류 남성의류 티셔츠
가이거  제니스시계 주얼리세트

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.07692307692307693
0.1
0.23076923076923078
0.26666666666666666
0.2857142857142857
0.3076923076923077

패션잡화 주얼리 주얼리세트 14K세트
뱅뱅 남성 간절기 데님팬츠  GQE772 GQE774 GQE776

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.05555555555555555
0.06666666666666667
0.4

패션의류 남성의류 청바지
크리스티나앤코 기모밴딩팬츠

HBox(children=(IntProgress(value=0, max=1227), HTML(value='')))

0.06666666666666667
0.08333333333333333
0.09090909090909091
0.13333333333333333
0.6363636363636364

패션의류 여성의류 바지

In [14]:
full_cat_df.to_csv('temp.csv',index='ignore')

NameError: name 'full_cat_df' is not defined

In [15]:
tmp = pd.merge(p_name,pd.concat([known,unknown]),left_on = 'After Process', right_on = 'pname').drop(['pname','pname2','After Process'],axis=1)
re_performance = pd.merge(performance,tmp,left_on='상품명',right_on='Before Process').drop(['Before Process'],axis=1)
re_performance.to_csv('categorized_performance.csv')

In [18]:
hyung = pd.read_csv('categorized_performance.csv')
hyein = pd.read_csv('categorized_performance_hyein.csv')

display(hyung.info())
display(hyein.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37372 entries, 0 to 37371
Data columns (total 16 columns):
Unnamed: 0      37372 non-null int64
방송일시            37372 non-null object
노출(분)           37372 non-null float64
상품명             37372 non-null object
상품군             37372 non-null object
판매단가            37372 non-null int64
취급액             37372 non-null float64
방송일시_yymmdd     37372 non-null object
방송일시_hhmmss     37372 non-null object
seconds         37372 non-null int64
방송일시_hhmm       37372 non-null object
ratings_mean    37372 non-null float64
cat1            37372 non-null object
cat2            37372 non-null object
cat3            36898 non-null object
cat4            23315 non-null object
dtypes: float64(3), int64(3), object(10)
memory usage: 4.6+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37372 entries, 0 to 37371
Data columns (total 16 columns):
Unnamed: 0      37372 non-null int64
방송일시            37372 non-null object
노출(분)           37372 non-null float64
상품명             37372 non-null object
상품군             37372 non-null object
판매단가            37372 non-null int64
취급액             37372 non-null float64
방송일시_yymmdd     37372 non-null object
방송일시_hhmmss     37372 non-null object
seconds         37372 non-null int64
방송일시_hhmm       37372 non-null object
ratings_mean    37372 non-null float64
cat1            37372 non-null object
cat2            37372 non-null object
cat3            36874 non-null object
cat4            23213 non-null object
dtypes: float64(3), int64(3), object(10)
memory usage: 4.6+ MB

None

In [52]:
hyein.head()

,Unnamed: 0,방송일시,노출(분),상품명,상품군,판매단가,취급액,방송일시_yymmdd,방송일시_hhmmss,seconds,방송일시_hhmm,ratings_mean,cat1,cat2,cat3,cat4,not_equal
0,0,2019-01-01 06:00:00,20.0,테이트 남성 셀린니트3종,의류,39900,2099000.0,2019-01-01,06:00:00,360,06:00,0.002255,패션의류,남성의류,니트/스웨터,NA,equal
1,1,2019-01-01 06:20:00,20.0,테이트 남성 셀린니트3종,의류,39900,3262000.0,2019-01-01,06:20:00,380,06:20,0.002210,패션의류,남성의류,니트/스웨터,NA,equal
2,2,2019-01-01 06:40:00,20.0,테이트 남성 셀린니트3종,의류,39900,6672000.0,2019-01-01,06:40:00,400,06:40,0.001997,패션의류,남성의류,니트/스웨터,NA,equal
3,3,2019-01-03 00:00:00,20.0,테이트 남성 셀린니트3종,의류,39900,7329000.0,2019-01-03,00:00:00,0,00:00,0.004875,패션의류,남성의류,니트/스웨터,NA,equal
4,4,2019-01-03 00:20:00,20.0,테이트 남성 셀린니트3종,의류,39900,10481000.0,2019-01-03,00:20:00,20,00:20,0.004736,패션의류,남성의류,니트/스웨터,NA,equal

In [54]:
hyein['same'] = '9999'

In [59]:
## 형주 kkma로 돌린 결과와 얼마나 틀린지 체크 !
hyung[['cat1','cat2', 'cat3', 'cat4']]= hyung[['cat1','cat2', 'cat3', 'cat4']].fillna('NA')
hyein[['cat1','cat2', 'cat3', 'cat4']] = hyein[['cat1','cat2', 'cat3', 'cat4']].fillna('NA')

for i in tqdm_notebook(range(len(hyung))):
    if hyung.cat1[i] != hyein.cat1[i]: 
        hyein['same'][i] = 'cat1'
    elif hyung.cat2[i] != hyein.cat2[i]:
        hyein['same'][i] = 'cat2'
    elif hyung.cat3[i] != hyein.cat3[i]:
        hyein['same'][i] = 'cat3'        
    elif hyung.cat4[i] != hyein.cat4[i]:
        hyein['same'][i] = 'cat4'
    else: 
        hyein['same'][i] = 'equal'

HBox(children=(IntProgress(value=0, max=37372), HTML(value='')))

C:\Users\heian\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\heian\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\heian\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\heian\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\heian\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

AttributeError: 'int' object has no attribute 'count_values'

In [60]:
hyein['same'].value_counts()

equal    35757
cat4       849
cat3       427
cat1       200
cat2       139
Name: same, dtype: int64